### ISSUE TITLE
support pre-release tags

### ISSUE THREAD

**Issue by GiladShoham** [zendesk/node-publisher#25]
Hi,
This tool looks very nice.
I would glad to see support for pre-release tag.
For example, I want to publish to dev / nightly tag in npm with a bit different process (other tests / skip git tag etc).
Thanks,
Gilad.

**Comment by vecerek** [comment]
Hi Gilad,
thank you very much for the proposal. I think it makes total sense. I'll prepare 2 PRs:

1. One that adds support for multiple release configs in the form of a `--config` option.
2. And one that removes the validation of the semver bump. I shouldn't have added it in the first place. `Lerna`, `npm` and `yarn` run their own validation against the version. In case it's not valid, they exit with an error. Then, `node-publisher` just rolls back and exits with a failure, too.

**Comment by vecerek** [comment]
Having the two above PRs merged, I think we can close this issue. Let me know in case you'd find any bugs or have other feature requests 🙂

**Comment by GiladShoham** [comment]
Thanks for this!
I'll check it out soon
